# Generated by Django 3.0.6 on 2020-06-30 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roastboast',
            name='score',
        ),
    ]
